language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls
